### PR TITLE
Add search feature to the site

### LINKED ISSUE #6: As a site visitor, I want to browse stories by text search via the front page of the site
- Implementation: Pelican tipue plugin

### PR DESCRIPTION
**Pull request by ammubhave**
Resolve #6

Hey, I am new comer to open-source! I wanted to contribute to the openhatch project. I added the pelican tipue plugin and it now uses it do to the search, tested and works.

### CODE REVIEW

**Comment by shaunagm** [comment]
Hi!  Thank you so much for contributing.  Some feedback on your pull request: we don't need the entire pelican-plugins directory here, we only need the specific plugins that we want to use, in this case Tipue search.  If you can remove all the extra files and resubmit, I should be able to merge it (though I will still need to test it).

**Comment by ammubhave** [comment]
Ok done, also I kept the sitemap plugin, because if it is not included then the build command gives warnings (which I am not sure why).

**Comment by shaunagm** [comment]
Looks great!  I was able to get it running without the sitemap plugin, so I've gone ahead and taken that out.

Can you comment on [this issue](https://github.com/openhatch/oh-contribution-stories/issues/27) to agree to the licensing agreement?

Also, let me know how you'd like to be credited for your contribution (full name, github name, link to personal website, etc).

**Comment by shaunagm** [comment]
@ammubhave, whenever you get the chance to sign the [licensing agreement](https://github.com/openhatch/oh-contribution-stories/issues/27), I am ready to merge this!  :)  Thanks again

**Pull request merged**
